### ISSUE TITLE
Add more linting options through a yml file

### ISSUE THREAD

**Issue by hiimbex** [probot/linter#7]
So, I've been looking for some probot stuff to hack on in my own time, and I think this plugin is RAD (albeit un-deployed), so I thought it would be cool to give people more options through a `/github/linter.yml` file that could include the properties here: https://standardjs.com/#is-there-a-nodejs-api

If this seems like a good idea, I'd love to work on it.

Thoughts @bkeepers ?

**Comment by bkeepers** [comment]
YES! That would be awesome!
